maintainers:
 - BurtonR
 - LucasRoesler
 - affix
 - alexellis
 - ewilde
 - ivanayov
 - johnmccabe
 - kenfdev
 - martindekov
 - matipan
 - rgee0
 - s8sg
 - stefanprodan
 - viveksyngh
 - zeerorg

features:
 - dco_check
 - comments
 - pr_description_required

custom_messages:
  - name: slack
    value: |
           --
           Join Slack to connect with the community
           https://docs.openfaas.com/community

contributing_url: https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md
